
- name: Install base packages
  hosts: lede
  gather_facts: no
  tasks:
    - name: light python
      raw: opkg update; opkg install python-light python-codecs python-logging python-openssl
    - name: install Ukrainian
      opkg: name=luci-i18n-base-uk state=present
  #- name: test
  #    raw: ping -c 4 google.com
