
- name: Install base packages
  hosts: lede
  gather_facts: no
  tasks:
    - name: light python
      raw: which python || (opkg update; opkg install python-light python-codecs python-logging python-openssl)
    - name: install base packages
      opkg: name={{ item }} state=present force=overwrite update_cache=yes
      with_items:
        - luci-i18n-base-uk
        - tmux
        - htop
