- name: Install and configure other services
  hosts: lede
  gather_facts: no
  tasks:
    - name: Install UVC driver
      opkg: name={{ item }} state=present force=overwrite update_cache=yes
      with_items:
        - kmod-video-uvc
        - kmod-video-core
        - mjpg-streamer
        - mjpg-streamer-input-uvc
        - mjpg-streamer-output-http
        - wakeonlan
      notify: Reload mjpg-streamer
    - name: mjpg-streamer service
      openwrt_init:
        name: mjpg-streamer
        state: started
        pattern: mjpg_streamer
        enabled: yes
    - name: Copy rc.local file
      copy: src=files/rc.local dest=/etc/rc.local owner=root mode=0640

  handlers:
    - name: Reload mjpg-streamer
      openwrt_init:
        name: mjpg-streamer
        state: reloaded
        pattern: mjpg_streamer
