
- name: Install and configure network services
  hosts: lede
  gather_facts: no
  tasks:
    - name: install network related packages
      opkg: name={{ item }} state=present force=overwrite update_cache=yes
      with_items:
        - 6in4
        - ddns-scripts
        - ddns-scripts_no-ip_com
        - openvpn-openssl
        - socat
        - tmux
        - tcpdump
        - snmpd
        - iputils-arping # required by snmpd_extend.sh
        - libustream-openssl20150806
#    - name: copy ddns file
#      copy: src=files/ddns dest=/etc/config/ddns owner=root mode=0640
      notify: enable and start ddns
    - name: copy snmpd file
      copy: src=files/snmpd dest=/etc/config/snmpd owner=root mode=0640
      notify: Reload SNMPD
    - name: copy snmpd_extend file # requires iputils-arping package
      copy: src=files/snmpd_extend.sh dest=/etc/config/snmpd_extend.sh owner=root mode=0755
      notify: Reload SNMPD

  handlers:
    - name: enable and start ddns
      shell: SRV=ddns; ls /etc/rc.d/ | grep -q $SRV || /etc/init.d/$SRV enable
    - name: Reload SNMPD
      openwrt_init:
        name: snmpd
        state: reloaded
        pattern: snmpd
