
- name: Install and configure network services
  hosts: lede
  gather_facts: no
  tasks:
    - name: install ddns packages
      action: >
        opkg name={{ item }} state=present update_cache=yes
      with_items:
        - ddns-scripts
        - ddns-scripts_no-ip_com
#    - name: copy ddns file
#      copy: src=files/ddns dest=/etc/config/ddns owner=root mode=0640
#      notify: enable and start ddns

  handlers:
    - name: enable and start ddns
      raw: /etc/init.d/ddns restart && /etc/init.d/ddns enable
