
- name: Install and configure network services
  hosts: lede
  gather_facts: no
  tasks:
    - name: install network related packages
      opkg: name={{ item }} state=present force=overwrite update_cache=yes
      with_items:
        - ddns-scripts
        - ddns-scripts_no-ip_com
        - openvpn-openssl
        - socat
        - 6in4
#    - name: copy ddns file
#      copy: src=files/ddns dest=/etc/config/ddns owner=root mode=0640
      notify: enable and start ddns

  handlers:
    - name: enable and start ddns
      shell: SRV=ddns; ls /etc/rc.d/ | grep -q $SRV || /etc/init.d/$SRV enable
