
- name: Install and configure storage
  hosts: lede
  gather_facts: no
  tasks:
    - name: install storage packages
      opkg: name={{ item }} state=present update_cache=yes
      with_items:
        - kmod-usb-storage
        - kmod-scsi-core
        - kmod-fs-ext4
        - e2fsprogs
        - block-mount
    - name: create dir 1
      file:
        path: /storage/1
        state: directory
    - name: create dir 2
      file:
        path: /storage/2
        state: directory
    - name: copy fstab file
      copy: src=files/fstab dest=/etc/config/fstab owner=root mode=0640
    - name: fstab service
      raw: /sbin/block mount
    - name: copy wait4mount file
      copy: src=files/wait4mount dest=/etc/init.d/wait4mount owner=root mode=0751
      notify: enable wait4mount
    - name: install SAMBA
      opkg: name=samba36-server state=present
    - name: copy samba file
      copy: src=files/samba dest=/etc/config/samba owner=root mode=0640
      notify: enable and start samba
    - name: install transmission packages
      opkg: name={{ item }} state=present update_cache=yes
      with_items:
        - transmission-daemon-mbedtls
        - transmission-web
      notify:
        - enable and start transmission

  handlers:
    - name: enable wait4mount
      shell: SRV=wait4mount; ls /etc/rc.d/ | grep -q $SRV || /etc/init.d/$SRV enable
    - name: enable and start samba
      shell: SRV=samba; ls /etc/rc.d/ | grep -q $SRV || /etc/init.d/$SRV enable; /etc/init.d/$SRV restart
    - name: enable and start transmission
      shell: SRV=transmission; ls /etc/rc.d/ | grep -q $SRV || /etc/init.d/$SRV enable; /etc/init.d/$SRV restart
